// <auto-generated />
using MakelaarLeaderboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakelaarLeaderboard.Migrations
{
    [DbContext(typeof(MakelaarLeaderboardContext))]
    partial class MakelaarLeaderboardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MakelaarLeaderboard.Models.House", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasTuin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MakelaarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MakelaarId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("MakelaarLeaderboard.Models.Makelaar", b =>
                {
                    b.Property<int>("MakelaarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MakelaarNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("MakelaarId");

                    b.ToTable("Makelaars");
                });

            modelBuilder.Entity("MakelaarLeaderboard.Models.House", b =>
                {
                    b.HasOne("MakelaarLeaderboard.Models.Makelaar", "Makelaar")
                        .WithMany("Houses")
                        .HasForeignKey("MakelaarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makelaar");
                });

            modelBuilder.Entity("MakelaarLeaderboard.Models.Makelaar", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
